### ISSUE TITLE
Fails install without '.' in @INC

### ISSUE THREAD

**Issue by kentfredric** [bigpresh/Pod-Readme#21]
On 5.25.10 with -Ddefault_inc_excludes_dot

```
Configuring Pod-Readme-1.001002 ... Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /home/kent/perl5/perlbrew/perls/5.25.10-nossp-sdbm-nopmc-nodot/lib/site_perl/5.25.10/x86_64-linux /home/kent/perl5/perlbrew/perls/5.25.10-nossp-sdbm-nopmc-nodot/lib/site_perl/5.25.10 /home/kent/perl5/perlbrew/perls/5.25.10-nossp-sdbm-nopmc-nodot/lib/5.25.10/x86_64-linux /home/kent/perl5/perlbrew/perls/5.25.10-nossp-sdbm-nopmc-nodot/lib/5.25.10) at Makefile.PL line 3.
BEGIN failed--compilation aborted at Makefile.PL line 3.
Configuring Pod-Readme failed.
```

**Comment by bigpresh** [comment]
I'm puzzled.

Pod::Readme appears to use EU::MM, not Module::Install; there's certainly no mention of Module::Install in its Makefile.PL (or, indeed, anywhere in the dist...)

Am I missing something obvious?

**Comment by bigpresh** [comment]
Ahh.  I'm looking at the code in my repo; @robrwo has since released a new version that does indeed use Module::Install.  If Rob is happy to be primary maintainer, it would make sense for the meta info for the dist to point to his repo and bug tracker.

**Comment by kentfredric** [comment]
@robrwo 's fork doesn't have issues open either, so its relying on him to check this issue tracker.

And because it was "forked" not "migrated", all these bugs are still here on this repo.

**Comment by bigpresh** [comment]
I'll speak to @robrwo separately and see what he wants to do; I suspect a reasonable course of action may be to fetch all his work since he forked from this repo into this one, then transfer it to him if he's happy to go on maintaining Pod::Readme - that way the open issues etc go with it.

Either way, we've got ourselves in a little bit of a mess, so we should sort it one way or another so we end up with one authoritative repo which the meta info in the dist refers to.

**Comment by karenetheridge** [comment]
FWIW this is why I use rt.perl.org as my bugtracker for all distributions :)

**Comment by toddr** [comment]
This is now failing on all perls above 5.26.0

**Comment by robrwo** [comment]
Hi. Yeah, things seem to be a bit confiused for this module. I was hoping to give maintenance over to podlators.

It needs a lot of work to fix it up.

**Comment by robrwo** [comment]
I will try and fix a few things as I have some extra time in the next couple of weeks, but PRs (@bigpresh's repo, not my form) are welcome.

**Comment by robrwo** [comment]
#24 switches to use Dist::Zilla, and this passes tests on my Perl 5.28. @karenetheridge I'd appreciate any feedback.
